server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 489620953466-203lok50ikrgmlm2pjon44gadar4ef84.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email


